// This component is completely generated by artificial intelligence.
import React, { useEffect, useRef, useState } from 'react';

import { motion, useAnimationFrame, useMotionValue } from 'motion/react';

interface TickerItem {
  id: string | number;
  content: React.ReactNode;
}

interface TickerProps {
  items: TickerItem[];
  speed?: number;
  pauseOnHover?: boolean;
  className?: string;
  bgColor?: string;
  direction?: 'left' | 'right';
}

const GAP_PX = 8;

const Ticker: React.FC<TickerProps> = ({
  items,
  speed = 60,
  pauseOnHover = true,
  className = '',
  bgColor = '',
  direction = 'left',
}) => {
  const viewportRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const markerRef = useRef<HTMLDivElement>(null);

  const [loopDistance, setLoopDistance] = useState(0);
  const [repeats, setRepeats] = useState(2);

  const x = useMotionValue(0);
  const progress = useRef(0);
  const paused = useRef(false);

  // calculate the width of one set + calculate the number of copies needed to fill the entire ticker
  useEffect(() => {
    const measure = () => {
      if (!viewportRef.current || !contentRef.current || !markerRef.current)
        return;

      const contentRect = contentRef.current.getBoundingClientRect();
      const markerRect = markerRef.current.getBoundingClientRect();
      const dist = markerRect.left - contentRect.left;
      if (dist <= 0) return;

      const viewportWidth = viewportRef.current.clientWidth;
      const needed = Math.max(2, Math.ceil(viewportWidth / dist) + 1);

      setLoopDistance((prev) => (prev !== dist ? dist : prev));
      setRepeats((prev) => (prev !== needed ? needed : prev));
    };

    measure();
    const ro = new ResizeObserver(measure);
    if (viewportRef.current) ro.observe(viewportRef.current);
    if (contentRef.current) ro.observe(contentRef.current);
    return () => ro.disconnect();
  }, [items]);

  // هر بار items/speed/direction عوض بشه یا فاصله‌ی حلقه تغییر کنه، از صفر شروع کن
  useEffect(() => {
    progress.current = 0;
    x.set(0);
  }, [items, speed, direction, loopDistance, x]);

  useAnimationFrame((_, delta) => {
    if (paused.current || !loopDistance) return;
    progress.current += speed * (delta / 1000);
    const wrapped = progress.current % loopDistance;
    x.set(direction === 'left' ? -wrapped : wrapped - loopDistance);
  });

  if (!items.length) return null;

  return (
    <div
      ref={viewportRef}
      className={`overflow-hidden whitespace-nowrap py-3 ${bgColor} ${className}`}
      onMouseEnter={() => pauseOnHover && (paused.current = true)}
      onMouseLeave={() => pauseOnHover && (paused.current = false)}
    >
      <motion.div
        ref={contentRef}
        className="inline-flex items-center"
        style={{ x, gap: `${GAP_PX}px` }}
      >
        {Array.from({ length: repeats }).map((_, setIndex) =>
          items.map((item, i) => (
            <div
              key={`${item.id}-${setIndex}`}
              ref={setIndex === 1 && i === 0 ? markerRef : undefined}
              className="flex items-center gap-3 shrink-0 text-sm md:text-base text-gray-100"
              aria-hidden={setIndex > 0 ? true : undefined}
            >
              {item.content}
            </div>
          )),
        )}
      </motion.div>
    </div>
  );
};

export default Ticker;
